
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    steps:
      name: Install node module
      - run: yarn install
      name: build static file
      - run: yarn run build
